FROM gcr.io/coinos-326717/github.com/tokenocean/raretoshi:base

ENV NODE_ENV staging

WORKDIR /app
COPY . .
RUN sed -i '/cypress/d' package.json
RUN pnpm i
RUN MODE=staging pnpm build

CMD ["node", "build"]
