FROM gcr.io/coinos-326717/github.com/tokenocean/raretoshi:base

ENV NODE_ENV staging

WORKDIR /app
COPY . .
RUN sed -i '/cypress/d' package.json
RUN sed -i 's/raretoshi.com/raretoshi.blockstream.com/g' .env.production
RUN NODE_ENV=development pnpm i
RUN pnpm build

CMD ["node", "build"]
