-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."announcements" add column "visible_end" timestamptz
--  not null default now();
