-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- create trigger check_bid after insert on transactions for each row execute procedure trigger_check_bid();
